### ISSUE TITLE
"ValueError: operands could not be broadcast together" raised when decomposing with odd frequencies

### ISSUE THREAD

**Issue by pmabbott** [alkaline-ml/pmdarima#316]
**Describe the bug**

Executing `arima.decompose` with `m` equal to an odd number (for example, `m=3`) throws an error `ValueError: operands could not be broadcast together with shapes (<N>,) (<N-1>,)` (Where `N` is the length of the data being decomposed).

**To Reproduce**  

```python
tarray =np.array([1.,2.,3.,4.,5.,6.,])
arima.decompose(tarray, 'additive', m=3)
```
**Versions**
```
System:
    python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
executable: C:\REDACTED_PATH_TO_A_VENV\python.exe
   machine: Windows-10-10.0.15063-SP0

Python dependencies:
        pip: 20.0.2
 setuptools: 46.1.3
    sklearn: 0.22.2.post1
statsmodels: 0.11.1
      numpy: 1.18.2
      scipy: 1.4.1
     Cython: 0.29.16
     pandas: 1.0.3
     joblib: 0.14.1
   pmdarima: 1.5.3
```

**Expected behavior**

Expected a decomposition of a trend with a seasonal period ("frequency") of some odd number of intervals.  Or at least a clearer explanation that `m` can only take even values.

**Actual behavior**
Function throws exception:
`ValueError: operands could not be broadcast together with shapes`

**Additional context**

I believe the issue comes from these parts of seasonality.py:

``` python
    # Take half of m for the convolution / sma process.
    half_m = m // 2
```
and 
``` python
    # We buffer the trend and seasonal components so that they are the same
    # length as the other outputs. This counters the effects of losing data
    # by the convolution/sma
    buffer = [np.nan] * half_m
    trend = list(buffer + trend.tolist() + buffer)
```

When `m` is odd, the length of `trend` is one shorter than `x` and therefore `m - trend` cannot be calculated.

I would guess that, for `m` odd, adding an extra `[np.nan]` to either the right hand buffer or the left hand buffer would fix the exception, but I don't follow the maths well enough to know if that would cause problems with the actual decomposition and/or whether this issue should be chased through to other sections of the code.

Exception thrown is very similar to that in #30 .
