### ISSUE TITLE
Accounting for multiple seasonalities ( Ex. Daily and Yearly) in Fourier Featurizer like msts() function in R

### ISSUE THREAD

**Issue by patelmohitj91** [alkaline-ml/pmdarima#392]
**Question**
I have been able to use the msts() function in R to model multiple seasonalities by building fourier features like so:

```r
logmsts <- log10(msts(y$cleandata, seasonal.periods = c(7,365.25)))
aicc_cals_temp <- NA
aicc_vals <-  NULL
for(j in 1:20) {
  for(i in 1:3) {
    dayyearfourier <- fourier(logmsts, K=c(i,j))
    fitAA4 <- auto.arima(logmsts,xreg=cbind(dayyearfourier,actual.holiday, actual.promo),seasonal=FALSE) 
    aicc_vals_temp <- cbind(i,j,fitAA4$aicc)
    aicc_vals <- rbind(aicc_vals,aicc_vals_temp)
  }
}
```

In the `pmdarima.preprocessing.FourierFeaturizer` class, we can model seasonalities by building a feature for one seasonality type but can we use it for multiple seasonalities by 2 or more function calls? 

**Versions (if necessary)**

```
System:
    python: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
executable: /local_disk0/pythonVirtualEnvDirs/virtualEnv-5f10633d-b2ed-4f41-8bf4-35bdb80e7981/bin/python
   machine: Linux-4.15.0-1092-azure-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
        pip: 20.0.2
 setuptools: 45.2.0
    sklearn: 0.22.1
statsmodels: 0.11.1
      numpy: 1.18.1
      scipy: 1.5.2
     Cython: 0.29.15
     pandas: 1.1.1
     joblib: 0.14.1
   pmdarima: 1.7.1
```
