### ISSUE TITLE
Absolute paths in source distribution prevent Windows installation

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [alkaline-ml/pmdarima#448]
**Describe the bug**

The source distribution published on PyPI contains the following absolute paths in `pmarima.egg-info/SOURCES.txt`:
```
/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h
/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/numpy/core/include/numpy/ufuncobject.h
```

This results in the following error when installing from the source distribution on Windows via `pip install .`:
```
    ValueError: path '/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h' cannot be absolute
    Running setup.py install for pmdarima ... error
```

**To Reproduce**  
- Download the[ source distribution](https://files.pythonhosted.org/packages/57/de/a4e2ff8fbebd783e4c9024ed73918f5d8ce0b38da6ef758e2c4d770f0358/pmdarima-1.8.2.tar.gz)
- Extract and open (Anaconda) Powershell in folder
```
pip install numpy~=1.19.0 Cython!=0.29.18,>=0.29
pip install . -vv
```

**Workarounds**
- Deleting the above mentioned paths from `SOURCES.txt` makes the source distribution installable.
- Deleting the `pmdarima.egg-info` folder makes the source distribution installable.

**Versions**

```
System:
    python: 3.9.6 (default, Aug 18 2021, 15:44:49) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\User\miniconda3\envs\pmdarima-build\python.exe
   machine: Windows-10-10.0.19043-SP0

Python dependencies:
        pip: 21.2.4
 setuptools: 52.0.0.post20210125
    sklearn: 0.24.2
statsmodels: 0.12.2
      numpy: 1.19.5
      scipy: 1.7.1
     Cython: 0.29.24
     pandas: 1.3.2
     joblib: 1.0.1
   pmdarima: 1.8.2
```

**Expected behavior**
An installable source distribution.

**Additional context**

I struggled with this when trying to add Windows support to the conda-forge package. I cannot reproduce the generation of a source distribution with such paths.
